# .streamlit/secrets.toml

# GitHub Personal Access Token (required for GitHub Models API calls)
GITHUB_API_KEY="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"